[package]
name = "kql-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.12.0"
miette = { version = "3.3.0", features = ["fancy"] }
thiserror = "1.0.30"

[dev-dependencies]
pretty_assertions = "1.1.0"
